'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { loadRazorpayScript } from '@/lib/razorpayBrowser';
interface Attempt {state:string;orderId?:string;paymentOrderId?:string;amount:number;keyId:string;currency:string;total:number;codAmount:number;items:{name:string;quantity:number}[]}
export default function RecoveryClient(){
 const [attempt,setAttempt]=useState<Attempt|null>(null),[reference,setReference]=useState(''),[message,setMessage]=useState('Checking your payment…'),[busy,setBusy]=useState(false);
 async function check(id:string){const r=await fetch(`/api/checkout/status?attemptId=${encodeURIComponent(id)}`);const data=await r.json();if(r.status===401){window.location.assign('/auth?redirect=/checkout/recover');return null;}if(!r.ok)throw new Error(data.error||'Could not check payment.');setAttempt(data);if(data.state==='completed'){sessionStorage.removeItem('doodleg-checkout-attempt');setMessage('Your order is confirmed.');}else if(data.state==='refunded')setMessage('This payment was refunded. Contact support for refund details.');else if(data.state==='needs_review')setMessage('Payment received. Support needs to review your order. Do not pay again.');else setMessage('This checkout is not yet confirmed. You can check again or resume the same payment below.');return data as Attempt;}
 useEffect(()=>{const id=sessionStorage.getItem('doodleg-checkout-attempt');if(!id){queueMicrotask(()=>setMessage('No interrupted checkout on this browser. Check your orders, or contact support with your payment reference.'));return;}queueMicrotask(()=>{setReference(id);void check(id).catch(e=>setMessage(e.message));});},[]);
 async function resume(){setBusy(true);try{const current=await check(reference);if(!current||current.state!=='pending'||!current.paymentOrderId)return;await loadRazorpayScript();if(!window.Razorpay)throw new Error('Payment window could not load.');new window.Razorpay({key:current.keyId,amount:current.amount,currency:current.currency,order_id:current.paymentOrderId,name:'Doodle G',description:'Resume your saved checkout',handler:async response=>{try{await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({razorpay:{orderId:response.razorpay_order_id,paymentId:response.razorpay_payment_id,signature:response.razorpay_signature}})});await check(reference);}catch{setMessage('Payment is processing. Check again before paying.');}}}).open();}catch(e){setMessage(e instanceof Error?e.message:'Could not resume payment.');}finally{setBusy(false);}}
 return <main className="mx-auto max-w-xl p-6"><Link href="/orders" className="underline">Your orders</Link><h1 className="my-6 text-3xl font-bold">Recover your checkout</h1><p role="status">{message}</p>{reference&&<p className="my-4 break-all text-sm text-gray-600">Reference: {reference}</p>}{attempt?.state==='pending'&&<section className="my-6 rounded-xl border p-5"><h2 className="font-semibold">Your saved order</h2><ul className="my-3">{attempt.items?.map((i,n)=><li key={n}>{i.quantity} × {i.name}</li>)}</ul><p>Order total: ₹{attempt.total}</p><p>Online: ₹{attempt.amount/100} · COD: ₹{attempt.codAmount}</p><button disabled={busy||!attempt.paymentOrderId} onClick={resume} className="mt-4 rounded bg-black px-4 py-3 text-white disabled:opacity-50">Resume this checkout</button></section>}{reference&&<button className="my-3 block underline" onClick={()=>check(reference).catch(e=>setMessage(e.message))}>Check payment again</button>}<Link href="/support" className="underline">Contact support</Link></main>;
}
