'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
interface Order { id:string;order_number:string;status:string;total_amount:number;placed_at:string;payment_method:string;online_amount?:number;cod_amount?:number;order_items?:{product_name:string;quantity:number;selected_size?:string}[];order_customization_items?:{product_name:string;quantity:number}[] }
export default function OrdersClient() {
 const [orders,setOrders]=useState<Order[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{ let active=true; Promise.all(['/api/orders','/api/customization-orders'].map(async url=>{const r=await fetch(url);if(r.status===401){window.location.assign('/auth?redirect=/orders');throw new Error('Sign in to view orders.');}if(!r.ok)throw new Error('Could not load orders. Please refresh.');return (await r.json()).orders as Order[];})).then(result=>{if(active)setOrders(result.flat().sort((a,b)=>b.placed_at.localeCompare(a.placed_at)));}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 return <main className="mx-auto max-w-3xl p-6"><nav className="mb-8 flex gap-5"><Link href="/shop">Shop</Link><Link href="/my-profile">Your profile</Link><Link href="/gifts">Gift plans</Link></nav><h1 className="text-3xl font-bold">Your orders</h1><p className="my-4 text-gray-600">Order confirmations and delivery status in one place.</p><Link className="underline" href="/checkout/recover">Check an interrupted payment</Link>{loading&&<p className="my-6">Loading orders…</p>}{error&&<p role="alert" className="my-6 text-red-700">{error}</p>}{!loading&&!error&&orders.length===0&&<p className="my-6">You haven’t placed an order yet.</p>}{orders.map(o=><article key={o.id} className="my-5 rounded-2xl border p-5"><h2 className="font-semibold">{o.order_number}</h2><p className="capitalize">{o.status} · ₹{Number(o.total_amount).toFixed(2)}</p>{Number(o.online_amount)>0&&Number(o.cod_amount)>0&&<p className="mt-2 text-sm">Paid online: ₹{Number(o.online_amount).toFixed(2)} · Due on delivery: ₹{Number(o.cod_amount).toFixed(2)}</p>}<ul className="my-3">{(o.order_items||o.order_customization_items||[]).map((i,n)=><li key={n}>{i.quantity} × {i.product_name}{'selected_size' in i&&i.selected_size?` · ${i.selected_size}`:''}</li>)}</ul><p className="text-sm text-gray-600">{new Date(o.placed_at).toLocaleDateString('en-IN')} · {o.payment_method}</p><Link className="mt-3 inline-block underline" href="/support">Get help with this order</Link></article>)}</main>;
}
