'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
interface Package {tier:string;title:string;estimatedPrice:number}
interface Recipient {id:string;name:string;orders:{id:string;status:string;selectedTier:string;giftPackages:Package[]}[]}
export default function GiftsClient(){
 const [recipients,setRecipients]=useState<Recipient[]>([]),[message,setMessage]=useState('Loading gift plans…'),[busy,setBusy]=useState('');
 useEffect(()=>{fetch('/api/dashboard').then(async r=>{if(r.status===401){window.location.assign('/auth?redirect=/gifts');return;}if(!r.ok)throw new Error();const data=await r.json();setRecipients(data.recipients);setMessage(data.recipients.length?'':'Add someone special to start a gift plan.');}).catch(()=>setMessage('Could not load gift plans. Please refresh.'));},[]);
 async function approve(orderId:string,selectedTier:string){setBusy(orderId);try{const r=await fetch('/api/update-order-tier',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderId,selectedTier})});if(!r.ok)throw new Error();setRecipients(rows=>rows.map(rec=>({...rec,orders:rec.orders.map(o=>o.id===orderId?{...o,status:'APPROVED',selectedTier}:o)})));setMessage('Gift preference saved. This does not charge you or place a shop order.');}catch{setMessage('Could not save this preference. Please retry.');}finally{setBusy('');}}
 return <main className="mx-auto max-w-3xl p-6"><nav className="mb-8 flex gap-5"><Link href="/shop">Shop</Link><Link href="/orders">Orders</Link><Link href="/onboarding">Add a gift plan</Link></nav><h1 className="text-3xl font-bold">Your gift plans</h1><p role="status" className="my-4">{message}</p>{recipients.map(rec=><section key={rec.id} className="my-6 rounded-2xl border p-5"><h2 className="text-xl font-semibold">{rec.name}</h2>{rec.orders.map(o=><div key={o.id}><p className="my-3">{o.status}{o.selectedTier?` · ${o.selectedTier}`:''}</p><div className="grid gap-3 sm:grid-cols-3">{o.giftPackages.map(p=><article key={p.tier} className="rounded-xl bg-gray-50 p-4"><h3 className="font-semibold">{p.title}</h3><p>{p.tier} · ₹{p.estimatedPrice}</p><button disabled={busy===o.id||o.status==='COMPLETED'} onClick={()=>approve(o.id,p.tier)} className="mt-3 rounded bg-black px-3 py-2 text-white disabled:opacity-50">Choose this gift</button></article>)}</div></div>)}</section>)}</main>;
}
